services:
  backend:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
  
  frontend:
    image: react
    build:
      context: ../../Frontend/client-application
      dockerfile: Dockerfile
    ports:
        - "3000:3000"

  db:
    image: postgres:latest
    environment:
        POSTGRES_DB: celladb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: '7034'
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
        - "6379:6379"
    volumes:
        - redis_data:/var/lib/redis/data
   
volumes:
  postgres_data:
  redis_data: 
